services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV: ${NODE_ENV}
      - PORT: ${PORT}
      - DB_TYPE: ${DB_TYPE}
      - DB_HOST: ${DB_HOST}
      - DB_PORT: ${DB_PORT}
      - DB_USERNAME: ${DB_USERNAME}
      - DB_PASSWORD: ${DB_PASSWORD}
      - DB_NAME: ${DB_NAME}
      - REDIS_HOST: ${REDIS_HOST}
      - REDIS_PORT: ${REDIS_PORT}
      - FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      - FIREBASE_WEB_API_KEY: ${FIREBASE_WEB_API_KEY}
      - SMTP_HOST: ${SMTP_HOST}
      - SMTP_PORT: ${SMTP_PORT}
      - SMTP_USER: ${SMTP_USER}
      - SMTP_PASS: ${SMTP_PASS}
      - SMTP_FROM: ${SMTP_FROM}
      - AUTO_SETUP_MULTITENANCY: ${AUTO_SETUP_MULTITENANCY}

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - package.json
            - package-lock.json
            - dist/
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
    depends_on:
      - postgres
      - redis  # Add this dependency

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine  # Use alpine for smaller size
    restart: unless-stopped
    volumes:
      - redis_data:/data  # Add this volume for data persistence
    ports:
      - '6378:6379'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL-admin@postgres.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD-admin}
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:  # Add this volume definition